Update luci-app-passwall2.yml

diff --git a/.github/workflows/luci-app-passwall2.yml b/.github/workflows/luci-app-passwall2.yml
--- a/.github/workflows/luci-app-passwall2.yml
+++ b/.github/workflows/luci-app-passwall2.yml
@@ -41,19 +41,19 @@ jobs:
       - name: Create install.sh scripts
         run: |
           cat <<EOF > passwall_x86_64/install.sh
-#!/bin/sh
-opkg update
-if [ \$? -ne 0 ]; then
-    echo "update failed。"
-    exit 1
-fi
-opkg install iptables-mod-tproxy
-opkg install iptables-mod-socket
-opkg install iptables-mod-iprange
-opkg install iptables-mod-conntrack-extra
-opkg install depends/*.ipk
-opkg install main/*.ipk
-EOF
+            #!/bin/sh
+            opkg update
+            if [ \$? -ne 0 ]; then
+                echo "update failed。"
+                exit 1
+            fi
+            opkg install iptables-mod-tproxy
+            opkg install iptables-mod-socket
+            opkg install iptables-mod-iprange
+            opkg install iptables-mod-conntrack-extra
+            opkg install depends/*.ipk
+            opkg install main/*.ipk
+            EOF
           chmod +x passwall_x86_64/install.sh
 
       - name: Move passwall2 directories to makeself
